name: lambdapic
dependencies:
  - python=3.12
  - mpi4py
  - h5py
  - numpy
  - numba
  - scipy
  - pip
  - sphinx==8.2.3
  - pip:
    - furo==2024.8.6
    - autodoc_pydantic==2.2.0
    - sphinxcontrib_mermaid==1.0.0
    - sphinx-copybutton==0.5.2